pipelines:
  branches:
    master:
      - step:
          name: ESLint code
          image: node:10.15.0
          caches:
            - node
          script:
            - npm ci
            - npm run check
      - step:
          name: Deploy to live
          deployment: production
          trigger: manual
          image: node:10.15.0
          script:
            - apt update
            - apt install -y bash python-pip jq bash curl
            - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            - unzip awscli-bundle.zip
            - ./awscli-bundle/install -b ~/bin/aws
            - export PATH=~/bin:$PATH
            - npm ci
            -  export ENVIRONMENT=alpha
            - ./deploy.sh alpha
    dev:
      - step:
          name: ESLint code
          image: node:10.15.0
          caches:
            - node
          script:
            - npm ci
            - npm run check
      - step:
          name: Deploy to dev
          deployment: test
          trigger: automatic
          image: node:10.15.0
          script:
            - apt update
            - apt install -y bash python-pip
            - apt install -y bash python-pip jq bash curl
            - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            - unzip awscli-bundle.zip
            - ./awscli-bundle/install -b ~/bin/aws
            - export PATH=~/bin:$PATH
            - export ENVIRONMENT=dev
            - npm ci
            - ./deploy.sh dev
  pull-requests:
    '**':
      - step:
          name: ESLint code
          image: node:10.15.0
          caches:
            - node
          script:
            - npm ci
            - npm run check